name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Plugin ZIP
        run: |
          # Kreiraj folder za ZIP
          mkdir d-express-woocommerce-integration

          # Kopiraj sve fajlove osim git i workflow foldera
          rsync -av --exclude='.git' --exclude='.github' ./ d-express-woocommerce-integration/

          # Ukloni nepotrebne fajlove
          rm -rf d-express-woocommerce-integration/.git*
          rm -rf d-express-woocommerce-integration/.github

          # Napravi ZIP
          zip -r d-express-woocommerce-integration.zip d-express-woocommerce-integration

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: d-express-woocommerce-integration.zip
          body: |
            ## Changelog
            - Poboljšanja u update mehanizmu
            - Optimizacije plugina
            - Додата подршка за аутоматско ажурирање
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
